mattes/migrate

- migrate/migrate.go
Looks like at some point nested errors were renamed to err2, but only the first instance was replaced (s/err/err2 instead of s/err/err2/g).
This causes improper error handling for nested errors. I think I got them all!
cheers!
> fix check on err when using err2

- main.go
the `ok` we fixed last time is actually a signal the pipe is closed. This doesn't mean there is necessarily an error, just that work is done. So, when we get this, we should return the current okFlag value, which lets us know if there were errors during execution.
cheers!
> ok flag is misleading, it's really if channel is closed, so return okFlag

- driver/cassandra/cassandra.go
Hi, 
This is my first pull request so let me know if I missed anything.
I had issue connecting to cassandra with native authenticator enabled. This pull request enable migrate to work when PasswordAuthenticator is enabled.
How to run..
migrate -url cassandra://username:password@hostname:port/schema_name-path ./cassandramigrations create init
Documentations url.
http://www.datastax.com/documentation/cassandra/2.0/cassandra/security/security_config_native_authenticate_t.htm
http://golang.org/pkg/net/url/#Userinfo
> Add authentication support for cassandra

- driver/driver.go
- driver/sqlite3/README.md
- driver/sqlite3/sqlite3.go
- driver/sqlite3/sqlite3_test.go
Addresses #2 [SQLite Driver](https://github.com/mattes/migrate/issues/2)
To be honest, this is pretty much a copy of the postgres driver. [mattn/go-sqlite3](https://github.com/mattn/go-sqlite3) supports multiple statements in the Exec function, so I copied postgres instead of MySQL.
Things to notice:
- Error messages could be improved. The library (sqlite, not go-sqlite3) does not tell you _where_ the error occurred, just that it did. 
- Third test in `sqlite3_test.go` --> The failure test from postgres/mysql actually does not cause an error in sqlite3 haha
I've used it a little bit for a toy project I'm working on, and it works, but I will admit it hasn't been really stress-tested.
> Add driver for sqlite3

- .travis.yml
This project depends on github.com/gocql/gocql, which does not support
go 1.2.
Update the .travis.yml file to match that reality.
Add go 1.4 and 1.5 to the test matrix.
> Fix travis build file to match reality

- file/file.go
- file/file_test.go
This is a proposed fix for #45 
I added a unit test to demonstrate the issue, and a proposed solution.  Both the test and the fix could be leveraged for more refactoring if that's of interest.
> Proposed fix for migration file name clashes

- .gitignore
- driver/driver.go
- driver/driver_test.go
This branch:
1. Streamlines the repetitive code in the driver switch statement by using a map of schemes to drivers.
2. Adds tests for the presence of drivers (just bash and sqlite3 as the larger systems obviously need a running instance of the particular database) as right now the test just checks for an invalid driver.
All tests passing, hope this helps!
> Streamline driver code

- README.md
- driver/bash/bash.go
- driver/cassandra/cassandra.go
- driver/driver.go
- driver/mysql/mysql.go
- driver/postgres/postgres.go
- driver/registry/registry.go
- driver/sqlite3/sqlite3.go
- migrate/migrate_test.go
Requires activating drivers with a _ style import, e.g.
`import _ " github.com/mattes/migrate/driver/postgres"`
I guess it's not fully backwards compatible (users will need to add the import for the driver they wish to use) but it avoids all dependencies being pulled in when they aren't needed.
> Don't load in all drivers by default #40

- docker-compose.yml
This should fix the failing builds.
> gocql doesn't support cassandra > 2.2

- docker-compose.yml
go-build container throws the following:
package github.com/mattn/go-sqlite3: C source files not allowed when not using cgo or SWIG: sqlite3-binding.c
> https://github.com/mattn/go-sqlite3 is cgo, so CGO_ENABLED must be true

- driver/cassandra/cassandra.go
I added this as a url query as I'm not sure of the backwards compatibility with previous version of the protocol, but I'm open to ideas
I'm also open to suggestions of testing, since the docker image isn't Cassandra 3, but I have testing with my cluster and it seems to work...
> Add support for Cassandra >= 3 with protocol version 4

- driver/cassandra/cassandra.go
Migrate is great. I love it. That said, my development environment doesn't have a full, multi-node Cassandra setup - I have one single container. This makes the default consistency of the Cassandra driver (`gocql.All`) problematic. So, I added a way to specify consistency in the connection string - the same way protocol may be specified. For example,
```
cassandra://localhost/SpaceOfKeys?protocol=4
cassandra://localhost/SpaceOfKeys?protocol=4&consistency=all
cassandra://localhost/SpaceOfKeys?consistency=quorum
```
This PR is a continuation of #112 (moved branches).
> Added consistency parameter to cassandra connection string

- migrate/migrate.go
If you don't use signal.Stop then this breaks Ctrl-C (at least on Windows) even after the migrations are finished.  Make sure to release them and it works as expected.
> Release OS signals when you're finished with them.

- Makefile
- driver/cassandra/cassandra_test.go
- driver/mysql/mysql_test.go
- driver/postgres/postgres_test.go
- driver/sqlite3/sqlite3_test.go
- migrate/migrate_test.go
- go-test target for local testing
> Skip tests requiring a DB connection with the '-short' flag

- docker-compose.yml
- migrate/migrate.go
- migrate/migrate_test.go
Using epoch prefixed filenames, multiple developers can commit migrations while minimizing versioning conflicts.
This commit remains backwards compatible with all previous migrations and requires no changes to the `schema_migrations` table.
This commit also cleans up migrate-test temp directories
> prefix migration files with epoch

- docker-compose.yml
- driver/crate/README.md
- driver/crate/crate.go
- driver/crate/crate_test.go
- main.go
This Pull Request adds a driver for the [Crate](https://crate.io) database. It has some limitations imposed by crate and the respective sql driver.
This Pull Request also contains a small change in the docker compose file, because the current docker-compose version (1.7.1) did complain about the syntax. Should be fine for older versions.
> Driver for the Crate.io database

- README.md
- driver/ql/README.md
- driver/ql/ql.go
- main.go
- migrate/migrate_test.go
Adds a driver for the embedded [Ql database](https://github.com/cznic/ql)
This is a little experimental, but it is working for my own basic usage and the migrate tests pass.
The url schemes had to be a little avant garde, (`ql+file://`, `ql+memory://`)  as else there would be no way of discerning that ql was the desired driver (the ql driver itself accepts just `file:///` and `memory://`).
> Add Ql driver

- driver/postgres/postgres.go
- driver/postgres/postgres_test.go
Uses a non-DDL select against information_schema to check for existence of version table.  If version table does exist, and if there are no schema migrations pending, no DDL statements are executed.
> Avoid DDL when checking for versions table #134

- main.go
Hopefully you don't mind a minor UI change, but I found it easier to read the migrate output when the up/down arrows (i.e. the `<` or `>`) in the output were different colors. So I changed them from both being blue to "up" being green and "down" being red.
Open to other suggestions if you like the idea but not the colors!
> Change colors for up and down migration arrows

- driver/cassandra/cassandra.go
- driver/cassandra/cassandra_test.go
Humbly offering a change whereby the Cassandra driver is changed to no longer use counters, relying instead on [select then update] which should be okay given that it only makes sense to run a single migration at a time.
Code tested with cassandra_test.go against scylla and cassandra.
> Add support for ScyllaDB (remove cql counter use)

- driver/neo4j/README.md
- driver/neo4j/neo4j.go
- driver/neo4j/neo4j_test.go
- main.go
This branch add the driver for Neo4j www.neo4j.com.
To test you can use ineo https://github.com/cohesivestack/ineo in order to install Neo4j: 
```
curl -sSL http://getineo.cohesivestack.com | bash -s install
```
```
source ~/.bashrc
```
```
ineo create test
```
1. Navigate to localhost:7474 in the web browser
2. Change the password to "test"
```
NEO4J_PORT_7474_TCP_ADDR=127.0.0.1 NEO4J_PORT_7474_TCP_PORT=7474 go test migrate/driver/neo4j
```
```
ineo uninstall
```
> Add driver for Neo4j

- pipe/pipe.go
Hi,
Like I said [here](https://github.com/mattes/migrate/issues/1#issuecomment-58728186), I had a problem interrupting my program when a migration successfully ran. I think the problem was that the interrupt signals were still being relayed to the interrupt channel created in the Up method of migrate.go.
That channel is passed to the WaitAndRedirect function of the Pipe. I added a simple function that is called after the function return to ensure the signals stop being relayed when the migration is over, successful or not.
What do you think? 
P.S. : I ran the test against a MySQL database where and everything was still fine.
Thanks, David
> Ensure that interrupt signals are not relayed to the interrupt channel when the migration is over

- driver/postgres/postgres.go
When running migrations in parallel on the same database but in different schemas, `ensureVersionTableExists` was schema-agnostic. This meant that having one `schema_migrations`, no matter in which schema, -could even be outside the search_path- would prevent the creation of more `schema_migrations` tables in different schemas.
I'm not sure whether the check should only look at the current schema or the whole search_path. For our use-case (testing packages in parallel using separate schemas) the former was sufficient, so I thought I'd open a PR for it.
> Postgres: version table existence check in current schema

- main.go
Avoid getting caught by go vet for using "\n" with Println
main.go:187: Println call ends with newline
> Fix for go vet

- driver/cassandra/cassandra.go
- driver/cassandra/cassandra_test.go
- driver/crate/crate.go
- driver/driver.go
- driver/mongodb/example/mongodb_test.go
- driver/mongodb/example/sample_mongdb_migrator.go
- driver/mongodb/gomethods/gomethods_migrator.go
- driver/mongodb/gomethods/gomethods_registry.go
- driver/mongodb/mongodb.go
- driver/neo4j/neo4j.go
- driver/postgres/postgres_test.go
- driver/ql/ql.go
- driver/registry.go
- driver/sqlite3/sqlite3.go
- driver/sqlite3/sqlite3_test.go
- file/file.go
- file/file_test.go
- main.go
- migrate/direction/direction.go
- migrate/migrate.go
- migrate/migrate_test.go
- pipe/pipe.go
- version.go
Fix golint errors and warnings. Cassandra driver was completely rewritten because of previous version that doesn't used migration file version. Previous version just  always increment counter, instead of write into db version of current schema state(last applied migration file version).
> Golint. Rewrite cassandra driver

- driver/sqlite3/sqlite3.go
It appears the sqlite3 lib has made breaking commits for this package:
https://github.com/mattn/go-sqlite3/commit/cf4bd560f1588d96c502b4c3407fe1a10cef4a28
https://github.com/mattn/go-sqlite3/commit/bd7fdb60336d54a68de20c03df2a036848e89eca
I was getting the following when trying to `go get` this tool:
```
go get -u github.com/mattes/migrate
../.go_workspace/src/github.com/mattes/migrate/driver/sqlite3/sqlite3.go:95: impossible type assertion:
sqlite3.Error does not implement error (Error method has pointer receiver)
go get -u github.com/mattes/migrate returned exit code 2
Action failed: go get -u github.com/mattes/migrate
```
Simple fix, change type assertion to use a pointer.
> driver/sqlite3: Fix for upstream changes

- driver/sqlite3/sqlite3.go
Seems the sqlite3 packaged reverted to using non-pointer Error. This patch corrects the use of it here.
This resolves issue #188
> fixing error cast for sqlite3

- driver/postgres/postgres.go
According to the PostgreSQL documentation (section 32.1.1.2), postgres library supports two URI schemes: postgresql:// and postgres://
Reference:
https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-CONNSTRING
> Support for alternative postgres URI scheme

- source/parse.go
- source/parse_test.go
Hi, 
Thank you for your work on this useful library,
I bumped into an issue when trying to use a date-based version (coming from a rails background) like "20170412214116_create_foo.up.sql" because a uint 32 is not enough to hold that number.
It's up to you if you think this is a valid golang use case, am just a newbie learning idiomatic go.
> Date-based versions

- database/mysql/mysql.go
Current mysql driver does not support multiple SQL statements in a single migration unless user manually sets `multiStatements=true` parameter in database DSN when **migrate** tool is executed.
Driver code tries to override this parameter to always be true but the parameter value is never saved back to the url struct.
This PR fixes this minor issue.
> Fix appending multiStatements=true parameter for mysql driver

- source/go-bindata/README.md
I was browsing this and noticed the typo that is causing syntax highlighting to be off.
> Fix a typo in go-bindata/README.md

- README.md
The example in README with file source doesn't work without importing "github.com/mattes/migrate/source/file" package.
> Add missing import to example in README

- driver/neo4j/neo4j.go
Neo4J supports both `http` and `https` connections, however `https`
connections weren't supported previously as the `neo4j` URL scheme
currently used to identify the driver type is always substituted for
just `http`.
This PR also registers the driver under an alternate key: `neo4js` which
given the way the scheme substitution happens, should allow the driver
to correctly create an `https` connection URL. This will allow the
library to be used for cases where we don't have access to the plain
`http` endpoint.
> Register neo4j driver using a pseudo `neo4js` protocol scheme.

- README.md
- cli/build_redshift.go
- database/redshift/README.md
- database/redshift/redshift.go
While Redshift is wire compatible with PostgreSQL, they support different functionality internally. 
Due to its distributed nature and being an OLAP database instead of a OLTP, Redshift does not in general support locking.
The upgraded PostgreSQL driver uses `pg_try_advisory_lock` in the `Lock()` and `Unlock()` functions, which is not supported by Redshift and causes and error.  This adds a Redshift-specific driver that wraps the standard PostgreSQL driver and overrides the `Lock()` and `Unlock()` to simply return `nil`.
> Added support for Redshift.

- cli/README.md
If the Go Postgres driver is not installed, then the example will fail. This commit adds the missing command.
> Add command to make CLI example with Go toolchain work

- database/mysql/mysql.go
In MySQL driver, lock name is purely determined by the database name.  However, it is quite common that multiple logical databases are physically backed by one single physical database. To make such logically isolated database migration work, we can specify different migration table for different logical database. The only problem is: migrating them in parallel will fail if another migrater holds the lock.
This change is to let lock name uses both database name and migration table name.
> Solve lock contention problem when upgrading multiple logical MySQL databases backed by a single physical database.

- .travis.yml
Tavis has updated its docker images, and as part of the update,
no longer includes support for the (deprevated) docker-engine
package, moving instead to docker-ce.
See https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch
for details of the package change.
This updates the travis configuration to pin the docker library
version to 17.05.0 and installs the corresponding version of
docker-ce in the install script.
> Update docker dependency version to fix Tavis builds

- database/spanner/spanner.go
I've got following message from the second time migration for Spanner.
```
2017/06/24 16:51:01 rpc error: code = InvalidArgument desc = Duplicate name in schema: SchemaMigrations. in line 0: CREATE TABLE SchemaMigrations (
Version INT64 NOT NULL,
Dirty    BOOL NOT NULL
) PRIMARY KEY(Version)
exit status 1
```
That's because not given existing column names causes `Invalid StreamingRead request` error in Spanner client and it is mistaken that the schema version table does not exist.
> Fix error due to duplicate schema version table for Spanner

- cli/README.md
- database/cockroachdb/README.md
- database/cockroachdb/cockroachdb.go
Adds a readme to the cockroachdb database package, following the
postgres readme style.
Also adds the ability to force acquisition of the migration lock
via a connect URL parameter/WithInstance config, to allow for fixing
cases where an implementation error causes the schema lock to not
be released.
Lastly, tweaks the CLI readme to include information on building a
CLI for databases other than postgres.
> Add cockroachdb README and add force lock functionality

- database/cockroachdb/cockroachdb.go
cockroach-go made a backwards-incompatible change to their transaction
function signatures, which was causing the cockroach instrumentation
to fail.
Updates the signature to match the cockraoch-go change.
> Update cockroachDB Txn signatures

- database/spanner/spanner.go
Support migration steps with multiple statements.
Migration steps with multiple statements currently fail with an error like `Syntax error on line x, column x: Expecting \'EOF\' but found an unknown character (\";\")`
**Example of a migration that currently fails:**
```SQL
CREATE TABLE table_name (
id STRING(255) NOT NULL,
) PRIMARY KEY(id);
CREATE INDEX table_name_id_idx ON table_name (id);
```
> (Spanner) Add support for multiple statements in one migration step
